name: secure_screen
description: A Flutter package for secure screen protection (screenshot and screen recording prevention).
version: 0.1.0
homepage: https://bitbucket.org/ninjafactory/secure-screen
license: MIT

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6

flutter:
  plugin:
    platforms:
      android:
        package: com.ninjafactory.secure_screen
        pluginClass: SecureScreenPlugin
      ios:
        pluginClass: SecureScreenPlugin

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


